name: minicpmembed
channels:
  - pytorch
  - nvidia
  - defaults
dependencies:
  - python=3.11
  - pip
  - faiss-gpu=1.13.0
  - mkl
  - pip:
      - diskannpy==0.7.0
      - accelerate==0.34.2
      - aiohappyeyeballs==2.4.6
      - aiohttp==3.11.12
      - aiosignal==1.3.2
      - async-timeout==5.0.1
      - attrs==25.1.0
      - certifi==2025.1.31
      - charset-normalizer==3.4.1
      - datasets==3.2.0
      - dill==0.3.8
      - fastzipfile==2.3.1
      - filelock==3.17.0
      - frozenlist==1.5.0
      - fsspec==2024.9.0
      - huggingface-hub==0.28.1
      - idna==3.10
      - jinja2==3.1.5
      - markupsafe==3.0.2
      - mpmath==1.3.0
      - multidict==6.1.0
      - multiprocess==0.70.16
      - networkx==3.4.2
      - numpy==2.2.3
      - nvidia-cublas-cu12==12.1.3.1
      - nvidia-cuda-cupti-cu12==12.1.105
      - nvidia-cuda-nvrtc-cu12==12.1.105
      - nvidia-cuda-runtime-cu12==12.1.105
      - nvidia-cudnn-cu12==9.1.0.70
      - nvidia-cufft-cu12==11.0.2.54
      - nvidia-curand-cu12==10.3.2.106
      - nvidia-cusolver-cu12==11.4.5.107
      - nvidia-cusparse-cu12==12.1.0.106
      - nvidia-nccl-cu12==2.20.5
      - nvidia-nvjitlink-cu12==12.8.61
      - nvidia-nvtx-cu12==12.1.105
      - pandas==2.2.3
      - peft==0.10.0
      - propcache==0.2.1
      - protobuf==3.20.0
      - psutil==7.0.0
      - pyarrow==19.0.0
      - python-dateutil==2.9.0.post0
      - pytz==2025.1
      - pyyaml==6.0.2
      - regex==2024.11.6
      - requests==2.32.3
      - safetensors==0.5.2
      - sentencepiece==0.2.0
      - six==1.17.0
      - soupsieve==2.6
      - sympy==1.13.3
      - tokenizers==0.15.2
      - torch==2.4.1
      - tqdm==4.67.1
      - transformers==4.37.2
      - triton==3.0.0
      - typing-extensions==4.12.2
      - tzdata==2025.1
      - urllib3==2.3.0
      - xxhash==3.5.0
      - yarl==1.18.3
      - uvicorn
      - fastapi
      - pydantic
